import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { mkdirSync, copyFileSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const pkgVersion = process.env.npm_package_version;
const outFile = prod ? `dist/${pkgVersion}/main.js` : "main.js";
if (prod) {
	// Ensure versioned dist directory exists
	mkdirSync(`dist/${pkgVersion}`, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outFile,
});

if (prod) {
	await context.rebuild();
	// Copy plugin assets to versioned dist
	copyFileSync("manifest.json", `dist/${pkgVersion}/manifest.json`);
	copyFileSync("styles.css", `dist/${pkgVersion}/styles.css`);
	process.exit(0);
} else {
	await context.watch();
}
